# functions.R
loadData_csv <- function() {
	read.csv(
	    "data/data.csv", 
	    colClasses=c(
			 project.number="factor",
			 asset.number="factor",
			 date="Date",
			 timestamp="POSIXct"
			 )
	    )
}

saveData_csv <- function(mydata) {
# take the data frame and save it to a CSV
	write.csv(mydata, "data/data.csv", row.names=F)
}

appendData <- function(mydata, data_proj){
# take the data frame and append the new data from the fields of the form
# (not sure if the input$xxx objects need to be inputs of this function...)

}

as.label <- function(num){
# take a number and convert it to a 4-character label
# throw a warning if the number is not between 0 and 9999
	n <- as.numeric(num)
	s <- paste("0000", n, sep="") # add on some padding 0's
	if (nchar(s)<5)
		warning("Converting an empty number into a label... This should never happen.")
	else if (is.na(n))
		stop("Cannot create a label from NA.")
	else if (n<0)
		warning("PATS labels should never be negative.")
	substring(s, nchar(s)-4+1) # return the last 4 chars
}

getAssetList <- function(mydata, PN, AN) {
	# take the data frame, project label, and asset label
	# return the list of assets in this form:
	# list(label= "0000", extension= "ASDF", name= <last-used name>)
	# expect the labels to be 4-character strings
	data_proj <- mydata[which(PN==mydata$project.number), ] # get matching project rows
	# cat("selecting assets\n")
	data_asset <- data_proj[which(AN==data_proj$asset.number), ] # get matching asset rows
	# str(data_asset)
	# print(data_asset)
	# cat("selecting latest asset\n")
	# cat(as.Date(data_asset$date, format="%Y-%m-%d"), "\n")
	ind <- sort.int(as.Date(data_asset$date, format="%Y-%m-%d"), index.return=T, decreasing=T)$ix
	if (length(ind)==sum(is.na(ind))) # if there are no valid dates
		ind <- nrow(data_asset) # just go with the last one in the data
	# cat("ind= ", ind, "\n")
	selected <- data_asset[ind[1], ] # take the latest observation
	# str(selected)
	# print(selected)
	list( # return this list
	     label= as.label(selected$asset.number),
	     extension= selected$extension,
	     name= as.character(selected$asset.name)
	     )
}

getProjectList <- function(mydata, PN){
# take the data frame and project label
# return the list of projects in this form:
# list(label= "0000", name= <name>, assets= <list of assets generated by getAssetList()>)
# expect the labels to be 4-character strings
	data_proj <- mydata[which(PN==mydata$project.number), ] # get matching project rows
	ind <- sort.int(as.Date(data_proj$date, format="%Y-%m-%d"), index.return=T, decreasing=T)$ix
	selected <- data_proj[ind[1], ] # take the latest observation
	asset_nums <- sort(levels(as.factor(data_proj$asset.number))) # sorted vector of proj's assets nums
	# cat("PN= ", PN, "\n")
	# cat("asset_nums= ", asset_nums, "\n")
	# str(asset_nums)
	assets <- lapply(asset_nums, function(x) getAssetList(data_proj, PN, x))
	list(
	     label= as.label(PN), 
	     name= selected$project.name,
	     assets= assets
	     )
}

generateIndex <- function(mydata){
# take the data frame of all the observations
# return a list of this form:
# list(data=list(NULL), projects= <list of projects generated by getProject()>)
	proj_nums <- sort(levels(as.factor(mydata$project.number)))
	projects <- lapply(proj_nums, function(x) getProjectList(mydata, x))
	list(
	     data= list(NULL), 
	     projects= projects
	     )
}




#### code to generate a sample index ####
# projNames <- c("lv3.0-airframe", "rv3k", "gps")
# projNums <- c(1,2,3)
# projects <- as.list(projNums)
# names(projects) <- projNames
# lv3 <- list(
# 	name= "lv3.0-airframe", 
# 	label= "0001", 
# 	assets= list(
# 		list(label="0001", name= "18 inch module"),
# 		list(label="0002", name= "24 inch module"),
# 		list(label="0003", name= "nosecone")
# 		)
# 	)
# rv3k <- list(name= "rv3k ", label= "0002", assets= list())
# gps <- list(name= "gps ", label= "0003", assets= list())
# 
# index$projects <- list(lv3, rv3k, gps)
# write(as.yaml(index), "data/index.yaml")
