# global.R
library("yaml")

index <- yaml.load_file("data/index.yaml")
projNums <- sapply(index$projects, function(x) x$label)
names(projNums) <- sapply(index$projects, function(x) x$name)

loadData_csv <- function() read.csv("data/sampleData.csv")

saveData_csv <- function(data) {
# take the data frame and save it to a CSV
}

loadData <- loadData_csv
saveData <- saveData_csv

appendData <- function(data){
# take the data frame and append the new data from the fields of the form
# (not sure if the input$xxx objects need to be inputs of this function...)
}

as.label <- function(num){
# take a number and convert it to a 4-character label
# throw a warning if the number is not between 0 and 9999
	n <- as.numeric(num)
	s <- paste("0000", n, sep="") # add on some padding 0's
	if (nchar(s)<5)
		warning("Converting an empty number into a label... This should never happen.")
	else if (is.na(n))
		stop("Cannot create a label from NA.")
	else if (n<0)
		warning("PATS labels should never be negative.")
	substring(s, nchar(s)-4+1) # return the last 4 chars
}

getAssetList <- function(data, PN, AN) {
	# take the data frame, project label, and asset label
	# return the list of assets in this form:
	# list(label= "0000", extension= "ASDF", name= <last-used name>)
	# expect the labels to be 4-character strings
	data_proj <- data[which(PN==data$project.number), ] # get matching project rows
	# cat("selecting assets\n")
	data_asset <- data_proj[which(AN==data_proj$asset.number), ] # get matching asset rows
	# str(data_asset)
	# print(data_asset)
	# cat("selecting latest asset\n")
	# cat(as.Date(data_asset$date, format="%Y-%m-%d"), "\n")
	ind <- sort.int(as.Date(data_asset$date, format="%Y-%m-%d"), index.return=T, decreasing=T)$ix
	if (length(ind)==sum(is.na(ind))) # if there are no valid dates
		ind <- nrow(data_asset) # just go with the last one in the data
	# cat("ind= ", ind, "\n")
	selected <- data_asset[ind[1], ] # take the latest observation
	# str(selected)
	# print(selected)
	list( # return this list
	     label= as.label(selected$asset.number),
	     extension= selected$extension,
	     name= as.character(selected$asset.name)
	     )
}

getProjectList <- function(data, PN){
# take the data frame and project label
# return the list of projects in this form:
# list(label= "0000", name= <name>, assets= <list of assets generated by getAssetList()>)
# expect the labels to be 4-character strings
	data_proj <- data[which(PN==data$project.number), ] # get matching project rows
	ind <- sort.int(as.Date(data_proj$date, format="%Y-%m-%d"), index.return=T, decreasing=T)$ix
	selected <- data_proj[ind[1], ] # take the latest observation
	asset_nums <- sort(levels(as.factor(data_proj$asset.number))) # sorted vector of proj's assets nums
	# cat("PN= ", PN, "\n")
	# cat("asset_nums= ", asset_nums, "\n")
	# str(asset_nums)
	assets <- lapply(asset_nums, function(x) getAssetList(data_proj, PN, x))
	list(
	     label= as.label(PN), 
	     name= selected$project.name,
	     assets= assets
	     )
}

generateIndex <- function(data){
# take the data frame of all the observations
# return a list of this form:
# list(data=list(NULL), projects= <list of projects generated by getProject()>)
	proj_nums <- sort(levels(as.factor(data$project.number)))
	projects <- lapply(proj_nums, function(x) getProjectList(data, x))
	list(
	     data= list(NULL), 
	     projects= projects
	     )
}


# updateIndex <- function(dat, index)
# {
# 
# 	projects <- levels(as.factor(dat$asset.number[which(dat$project.number == prj$label)]))
# 	l <- list()
# 	for (prj in projects)
# 	{
# 
# 	}
# 	
# 	return(newind)
# }

# df2nested <- function(dat, hier)
# {
# 	lev <- levels(as.factor(dat[[heir[0]]]))
# 	l <- list()
# 	names(l) <- rep(heir[1], length(l))
# }

# printElem <- function(l, n=0)
# {
# 	out <- NULL
# 	if (typeof(l)=="list" && length(l)>0)
# 	{
# 		cat("names of l: \n", names(l), "\n")
# 		for (i in 1:length(l))
# 		{
# 			out <- paste(sep="", 
# 				      out, 
# 				      rep("  ", n), names(l)[i], "\n",
# 				      rep("  ", n+1), printElem(l[[i]], n+1), "\n"
# 			      )
# 		}
# 	} else {
# 
# 		cat(names(l), ": ", l, "\n")
# 		out <- l
# 	}
# 	return(out)
# }

# lookupProj <- function(pnum, input){
# 	projInd <- which(sapply(
# 			index$projects, 
# 			function(x) x$label==input$pnum
# 			))
# 	currentProjAssets <- sapply(
# 				index$projects[[projInd]]$assets, 
# 				function(x) x$label
# 				)
# 	names(currentProjAssets) <- paste(
# 			currentProjAssets,
# 			sapply(
# 				index$projects[[projInd]]$assets, 
# 				function(x) x$name
# 				),
# 			sep= " -- "
# 			)
# }

# projNames <- c("lv3.0-airframe", "rv3k", "gps")
# projNums <- c(1,2,3)
# projects <- as.list(projNums)
# names(projects) <- projNames
# lv3 <- list(
# 	name= "lv3.0-airframe", 
# 	label= "0001", 
# 	assets= list(
# 		list(label="0001", name= "18 inch module"),
# 		list(label="0002", name= "24 inch module"),
# 		list(label="0003", name= "nosecone")
# 		)
# 	)
# rv3k <- list(name= "rv3k ", label= "0002", assets= list())
# gps <- list(name= "gps ", label= "0003", assets= list())
# 
# index$projects <- list(lv3, rv3k, gps)
# write(as.yaml(index), "data/index.yaml")
