# global.R
library("yaml")

index <- yaml.load_file("data/index.yaml")
projNums <- sapply(index$projects, function(x) x$label)
names(projNums) <- sapply(index$projects, function(x) x$name)

loadData <- loadData_csv
saveData <- saveData_csv

loadData_csv <- function() read.csv("data/sampleData.csv")

saveData_csv <- function(data) {
# take the data frame and save it to a CSV
}

appendData <- function(data){
# take the data frame and append the new data from the fields of the form
# (not sure if the input$xxx objects need to be inputs of this function...)
}

num2lab <- function(num){
# take a number and convert it to a 4-character label
# throw a warning if the number is not between 0 and 9999
}

getAsset <- function(data, project.label, asset.label) {
# take the data frame, project label, and asset label
# return the list of assets in this form:
# list(label= "0000", extension= "ASDF", name= <last-used name>)
# expect the labels to be 4-character strings
}

getProject <- function(data, project.label){
# take the data frame and project label
# return the list of projects in this form:
# list(label= "0000", name= <name>, assets= <list of assets generated by getAsset()>)
# expect the labels to be 4-character strings
}

updateIndex <- function(data){
# take the data frame of all the observations
# return a list of this form:
# list(data=list(NULL), projects= <list of projects generated by getProject()>)
}


# updateIndex <- function(dat, index)
# {
# 
# 	projects <- levels(as.factor(dat$asset.number[which(dat$project.number == prj$label)]))
# 	l <- list()
# 	for (prj in projects)
# 	{
# 
# 	}
# 	
# 	return(newind)
# }

# df2nested <- function(dat, hier)
# {
# 	lev <- levels(as.factor(dat[[heir[0]]]))
# 	l <- list()
# 	names(l) <- rep(heir[1], length(l))
# }

# printElem <- function(l, n=0)
# {
# 	out <- NULL
# 	if (typeof(l)=="list" && length(l)>0)
# 	{
# 		cat("names of l: \n", names(l), "\n")
# 		for (i in 1:length(l))
# 		{
# 			out <- paste(sep="", 
# 				      out, 
# 				      rep("  ", n), names(l)[i], "\n",
# 				      rep("  ", n+1), printElem(l[[i]], n+1), "\n"
# 			      )
# 		}
# 	} else {
# 
# 		cat(names(l), ": ", l, "\n")
# 		out <- l
# 	}
# 	return(out)
# }

# lookupProj <- function(pnum, input){
# 	projInd <- which(sapply(
# 			index$projects, 
# 			function(x) x$label==input$pnum
# 			))
# 	currentProjAssets <- sapply(
# 				index$projects[[projInd]]$assets, 
# 				function(x) x$label
# 				)
# 	names(currentProjAssets) <- paste(
# 			currentProjAssets,
# 			sapply(
# 				index$projects[[projInd]]$assets, 
# 				function(x) x$name
# 				),
# 			sep= " -- "
# 			)
# }

# projNames <- c("lv3.0-airframe", "rv3k", "gps")
# projNums <- c(1,2,3)
# projects <- as.list(projNums)
# names(projects) <- projNames
# lv3 <- list(
# 	name= "lv3.0-airframe", 
# 	label= "0001", 
# 	assets= list(
# 		list(label="0001", name= "18 inch module"),
# 		list(label="0002", name= "24 inch module"),
# 		list(label="0003", name= "nosecone")
# 		)
# 	)
# rv3k <- list(name= "rv3k ", label= "0002", assets= list())
# gps <- list(name= "gps ", label= "0003", assets= list())
# 
# index$projects <- list(lv3, rv3k, gps)
# write(as.yaml(index), "data/index.yaml")
